# base image
FROM python:3.8.1-slim

# install netcat
RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean

# set working directory
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add deploy.sh
COPY ./deploy.sh /usr/src/app/deploy.sh
RUN chmod +x /usr/src/app/deploy.sh

# add app
COPY . /usr/src/app

# run server
CMD ["/usr/src/app/deploy.sh"]
